### ISSUE TITLE
Database UI doesn't account for Editor Display Scale

### ISSUE THREAD

**Issue by Phanterm** [DarthPapalo666/ResourceDatabases#1]
![image](https://github.com/user-attachments/assets/609ccb1d-f5c2-4a88-b360-213763b43791)

Not sure how one accounts for this, but it looks like the UI does not account for the current Display Scale in the Editor settings. (mine is 125%).

Comparing this to the video of the initial plugin, it looks like this not only affects the popup windows, but the margins between DB items under the Collections panel.

**Comment by DarthPapalo** [comment]
Will look into this today, thanks for the feedback!

EDIT: Just had a quick look, and changed my scale to 125%. Everything seems to work fine except for the warning dialogue and the collection buttons on the left. I will push a fix later together with some documentation.

**Comment by DarthPapalo** [comment]
Well, I just fixed the start screen scale by adding an AspectRatioContainer. This might be a solution for basically everything inside the plugin to be able to support several editor scales.
