### ISSUE TITLE
[Suggestion] Populate Resource-specific properties in Collections as columns

### ISSUE THREAD

**Issue by Phanterm** [DarthPapalo666/ResourceDatabases#2]
# Summary 
I was super excited for this plugin, but, unless I'm not using it correctly, it's missing the key reason why I'd want my database within Godot -- to make use of seeing all of my data at a glance.

## Problem
As a game designer, I have a lot of Resource data like attacks or enemy templates, and balancing this amount of game becomes a big task, especially when you have to hunt down the right Resource, change it, track down other Resources to make sure the numbers compare favorably, etc.

I currently use a Google Sheets document and write custom importers as an `EditorScript` within Godot to bring my data into the engine. But that isn't perfect, especially when you're tweaking and iterating while in play mode. Because if you import again, you either overwrite your old data, unless you specifically tag entries you want to exclude and integrate that into your importer, or always be sure to update the external database if you ever change anything. That's a lot.

## Solution
Well, if the data that populated your database were the Resources themselves, that eliminates the need to use CSV importers or ensure you're always at 1:1 parity with your external data. If I could expose something like the `damage` variable from the `AttackTemplate` entries in a Collection, and then be able to sort entries by that, I'd be ecstatic.

## Implementation
Since Resources can have any number of properties, the way I would expect something like this to work would be to choose one of the Resource types in the current Collection, and then select one or more properties you would like to expose represented as a column.

Here's a rough edit to demonstrate what I mean.
![image](https://github.com/user-attachments/assets/23d35695-d62f-4c9c-864c-fe24d9644fe2)

And the way that `AnimationPlayer` enables you to create property tracks and select the node + property is how I imagine this might(?) look. Sadly, I don't know much of anything about working with Godot's interface and plugins.
![image](https://github.com/user-attachments/assets/3cddad0e-5f2c-4998-a283-2e16a5c59479)

I don't mean to put the cart before the horse, since sorting isn't even a feature here 😅 I just wanted to weigh in on something that would, for me, really put a plugin like this over the top.

**Comment by DarthPapalo** [comment]
Thanks for the feedback! This plugin aims to help with the **accessing** of resources at runtime, so editing them within the database plugin would be an overkill for its purpose ( @don-tnowe has an awesome "Edit Resources as Table 2" plugin that can help you with the editing of multiple resources) .

What I think I can add is a way of filtering resources by an expression (i.e. "damage == 2" or "damage" > 5). But note this would only work by checking if a resource has the property "damage" (If you restrict the collection to a certain type of resource that has this property then it would be guaranteed to work).

I was planning to make this a feature a long a ago so you can expect me to push a commit for this soon (I hope is not very difficult to implement haha). The point is that my plugin still won't provide an editing tool, apart from the ability to easily open a resource in the built-in inspector using the button on the right of each entry.
