### ISSUE TITLE
Database only readonly from scripts?

### ISSUE THREAD

**Issue by LonelyGriffin** [DarthPapalo666/ResourceDatabases#7]
[Database resource](https://github.com/DarthPapalo666/ResourceDatabases/blob/main/addons/resource_databases/database.gd) has only read methods. How can  I write new entry or collection from script?

**Comment by DarthPapalo** [comment]
The only intended way of editing a Database is by using the database editor provided with the plugin. You could technically edit one with scripts using the DatabaseIO and EditorDatabase classes but this was never intended to be exposed (I could try to expose some methods and document this way of doing it).

If you mean editing the databases in-game, this plugin does not provide that, it's only intended for managing static data (Data that won't change during runtime).
